apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: mongodb-exporter
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-09-26T16:08:27Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: mongodb-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-mongodb-exporter
    helm.sh/chart: prometheus-mongodb-exporter-2.8.1
    release: prometheus
  name: mongodb-exporter-prometheus-mongodb-exporter
  namespace: default
  resourceVersion: "389749"
  uid: 8fdfffd6-7b37-4872-b68a-a63c3bc7f9a5
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb-exporter
      app.kubernetes.io/name: prometheus-mongodb-exporter
